spring.application.name=employee-service
spring.profiles.active=dev

# We removed 'optional:' so it will crash and give us an error if it fails!
spring.config.import=configserver:http://localhost:8888