# Standard port for Spring Cloud Config Server
server.port=8888
spring.application.name=config-server

# Tell it to read from the local file system (our shared-config folder) instead of GitHub
spring.profiles.active=native

# Point it to the folder we created
spring.cloud.config.server.native.search-locations=classpath:/shared-config


