# 1. Force the internal hostname to localhost
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

# 2. Manually override the Instance ID so it stops using mshome.net
eureka.instance.instance-id=${spring.application.name}:${server.port}

# 3. Command Spring Cloud to completely ignore Docker/WSL virtual network adapters
spring.cloud.inetutils.ignored-interfaces=vEthernet.*

# Force Micrometer to trace 100% of incoming requests
management.tracing.sampling.probability=1.0

# --- REDIS BASE CONFIGURATION ---
spring.data.redis.host=localhost
spring.data.redis.port=6379