server.port=8085
spring.application.name=audit-service

# Config Server Import (Mandatory for Spring Boot 3)
spring.config.import=optional:configserver:http://localhost:8888

# Usually best to disable Eureka registration during local testing
eureka.client.enabled=false